[package]
name = "async_rust_cli"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["sncf"]

[dependencies]
anyhow = "1.0.100"
dotenvy = "0.15.7"
sncf = { path = "sncf" }


[dev-dependencies]
pretty_assertions = "1.4.1"
